version: '3'

services:
  ui:
    build:
      context: ./
      dockerfile: ./docker/ui/Dockerfile
    ports:
      - 80:80
      - 3000:3000
    networks:
      - database-network

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 5000:5000
    networks:
      - database-network

  mongo:
    image: mongo
    restart: always
    volumes:
      - db-store:/data/db
    networks:
      - database-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - database-network
    depends_on:
      - mongo

volumes:
  db-store:

networks:
  database-network: